export interface VisibleAttribute{
    ID:number,
    ProductID:number,
    VariantID:number,
    AttributeID:number,
    AttributeOptionID:string,
    AttributeOptionCode:string,
    OptionDisplayOrder:number,
    CustomValueText:string,
    Style:string,
    Description:string,
    CodeName:string,
    DisplayName:string,
    DisplayOrder:number,
    IsVariant:boolean,
    IsFilter: boolean,
    IsDetailAtribute: boolean,
    IsSearchAttribute:boolean,
    IsImageSwitcher:boolean,
    IsLookup:boolean,
    IsVisibleToCustomer:boolean,
    IsTemplateAttribute:boolean,
    ValueText:string,
    AttributeLogo:string,
    IsClassification:boolean,
    ActualValueText:string,
    Quantity:string,
    ImageUrl:string
}